version: '3'

services:
  backend:
    build: ./backend
    expose: 
      - 3333
    ports:
      - 3333:3333
    volumes:
      - ./backend/.env.example:/backend/.env
    command: npm run dev
  
  frontend:
    build: ./frontend
    expose: 
      - 3000
    ports:
      - 3000:3000
    links:
      - backend
    command: npm run dev