import Head from 'next/head'
import IPListSectionComponent from '../components/IPListSectionComponent'
import NavBarComponent from '../components/NavBarComponent'
import TopSectionComponent from '../components/TopSectionComponent'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous"
        />
      </Head>

      <main>
        <NavBarComponent></NavBarComponent>
        <TopSectionComponent></TopSectionComponent>
        <IPListSectionComponent></IPListSectionComponent>
      </main>

      <footer>
        <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin></script>
        <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js" crossorigin></script> 
        <script src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js" crossorigin></script> 
      </footer>
    </div>
  )
}

